//
// File: collisionflags.h
//
// Copyright (C) 2023-2024 ranstar74. All rights violated.
//
// Part of "Rage Am" Research Project.
//
#pragma once

#include "common/types.h"

#include "am/system/enum.h"

namespace rage
{
	// In source code, flags are stored in ArchetypeFlags namespace and have GTA_ prefix,
	// but in RDR3 R* refactored them in separate enum:
	// https://alexguirre.github.io/rage-parser-dumps/dump.html?game=rdr3&build=1491&search=collisionf#eCollisionFlags

	enum eCollisionFlags : u32
	{
		CF_NONE                 = 0,
		CF_UNUSED               = 1 << 0,
		CF_MAP_TYPE_WEAPON      = 1 << 1,
		CF_MAP_TYPE_MOVER       = 1 << 2,
		CF_MAP_TYPE_HORSE       = 1 << 3,
		CF_MAP_TYPE_COVER       = 1 << 4,
		CF_MAP_TYPE_VEHICLE     = 1 << 5,
		CF_VEHICLE_NON_BVH_TYPE = 1 << 6,
		CF_VEHICLE_BVH_TYPE     = 1 << 7,
		CF_BOX_VEHICLE_TYPE     = 1 << 8,
		CF_PED_TYPE             = 1 << 9,
		CF_RAGDOLL_TYPE         = 1 << 10,
		CF_HORSE_TYPE           = 1 << 11,
		CF_HORSE_RAGDOLL_TYPE   = 1 << 12,
		CF_OBJECT_TYPE          = 1 << 13,
		CF_ENVCLOTH_OBJECT_TYPE = 1 << 14,
		CF_PLANT_TYPE           = 1 << 15,
		CF_PROJECTILE_TYPE      = 1 << 16,
		CF_EXPLOSION_TYPE       = 1 << 17,
		CF_PICKUP_TYPE          = 1 << 18,
		CF_FOLIAGE_TYPE         = 1 << 19,
		CF_FORKLIFT_FORKS_TYPE  = 1 << 20,
		CF_WEAPON_TEST          = 1 << 21,
		CF_CAMERA_TEST          = 1 << 22,
		CF_AI_TEST              = 1 << 23,
		CF_SCRIPT_TEST          = 1 << 24,
		CF_WHEEL_TEST           = 1 << 25,
		CF_GLASS_TYPE           = 1 << 26,
		CF_RIVER_TYPE           = 1 << 27,
		CF_SMOKE_TYPE           = 1 << 28,
		CF_UNSMASHED_TYPE       = 1 << 29,
		CF_STAIR_SLOPE_TYPE     = 1 << 30,
		CF_DEEP_SURFACE_TYPE    = 1 << 31u,

		CF_ALL					= (1 << 32) - 1,
	};
	using CollisionFlags = u32;

	inline ConstString ToString(eCollisionFlags e);
	inline bool FromString(ConstString str, eCollisionFlags& e);
	IMPLEMENT_FLAGS_TO_STRING(eCollisionFlags, "CF_");

	// Compilations of the above type flags into type sets

	enum : u32
	{
		// Basic combinations
		CF_VEHICLE_TYPE = CF_VEHICLE_NON_BVH_TYPE | CF_VEHICLE_BVH_TYPE | CF_WHEEL_TEST,
		CF_ALL_MAP_TYPES = CF_MAP_TYPE_MOVER,
		CF_ALL_TYPES_MOVER = CF_MAP_TYPE_MOVER | CF_VEHICLE_TYPE | CF_PED_TYPE | CF_OBJECT_TYPE | CF_PICKUP_TYPE | CF_GLASS_TYPE | CF_RIVER_TYPE,
		CF_ALL_TYPES_WEAPON = CF_MAP_TYPE_WEAPON | CF_VEHICLE_NON_BVH_TYPE | CF_VEHICLE_BVH_TYPE | CF_PED_TYPE | CF_OBJECT_TYPE | CF_PICKUP_TYPE | CF_GLASS_TYPE | CF_RIVER_TYPE,
		CF_ALL_SHAPETEST_TYPES = CF_WEAPON_TEST | CF_CAMERA_TEST | CF_AI_TEST | CF_SCRIPT_TEST | CF_WHEEL_TEST,
		CF_CORE_SHAPETEST_TYPES = CF_WEAPON_TEST | CF_AI_TEST | CF_SCRIPT_TEST | CF_WHEEL_TEST,

		// Include sets for base game objects
		CF_BUILDING_INCLUDE_TYPES = CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_PLANT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_VEHICLE_INCLUDE_TYPES = CF_MAP_TYPE_VEHICLE | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_ENVCLOTH_OBJECT_TYPE | CF_PLANT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_PICKUP_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_FOLIAGE_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE | CF_SMOKE_TYPE,
		CF_BOX_VEHICLE_INCLUDE_TYPES = CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_WEAPON_TEST | CF_AI_TEST | CF_SCRIPT_TEST | CF_GLASS_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_PED_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_ENVCLOTH_OBJECT_TYPE | CF_PLANT_TYPE | CF_PROJECTILE_TYPE | CF_PICKUP_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_FOLIAGE_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_RAGDOLL_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_ENVCLOTH_OBJECT_TYPE | CF_PLANT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_FOLIAGE_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE | CF_SMOKE_TYPE | CF_DEEP_SURFACE_TYPE,
		CF_ENVCLOTH_OBJECT_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_GLASS_TYPE | CF_WEAPON_TEST | CF_HORSE_RAGDOLL_TYPE,
		CF_PARACHUTING_PED_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_BOX_VEHICLE_TYPE | CF_OBJECT_TYPE | CF_GLASS_TYPE,
		CF_OBJECT_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_PLANT_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,

		// Include sets for special game objects
		CF_DOOR_OBJECT_INCLUDE_TYPES = CF_VEHICLE_TYPE | CF_VEHICLE_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_EXPLOSION_TYPE | CF_PROJECTILE_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_PROJECTILE_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_EXPLOSION_TYPE | CF_PICKUP_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_PROJECTILE_NEAR_INCLUDE_TYPES = CF_MAP_TYPE_WEAPON | CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_EXPLOSION_TYPE | CF_PICKUP_TYPE | CF_ALL_SHAPETEST_TYPES | CF_GLASS_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_EXPLOSION_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_BOX_VEHICLE_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_PROJECTILE_TYPE | CF_PICKUP_TYPE | CF_GLASS_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_SMOKE_INCLUDE_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_NON_BVH_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_VEH_SEAT_INCLUDE_FLAGS = (CF_VEHICLE_INCLUDE_TYPES & ~CF_ALL_SHAPETEST_TYPES),
		CF_WHEEL_INCLUDE_TYPES = (CF_VEHICLE_INCLUDE_TYPES & ~(CF_WHEEL_TEST | CF_PICKUP_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_CAMERA_TEST)),	// Wheels collide with everything vehicles do
		CF_VEH_BVH_CHASSIS_INCLUDE_TYPES = CF_VEHICLE_NON_BVH_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_PROJECTILE_TYPE | CF_ALL_SHAPETEST_TYPES | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_CAR_DOOR_UNLATCHED_INCLUDE_TYPES = CF_VEHICLE_INCLUDE_TYPES,
		CF_CAR_DOOR_LATCHED_INCLUDE_TYPES = CF_CORE_SHAPETEST_TYPES | CF_PROJECTILE_TYPE,
		CF_CAR_BUMPER_INCLUDE_TYPES = CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_ALL_SHAPETEST_TYPES | CF_VEHICLE_NON_BVH_TYPE,

		// Include sets for world probe type tests
		CF_MELEE_VISIBILTY_TYPES = CF_ALL_MAP_TYPES | CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_OBJECT_TYPE | CF_GLASS_TYPE,
		CF_WEAPON_TYPES = CF_VEHICLE_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_PROJECTILE_TYPE | CF_GLASS_TYPE | CF_MAP_TYPE_WEAPON | CF_RIVER_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_MOBILE_ACTORS_TYPES = CF_VEHICLE_NON_BVH_TYPE | CF_FORKLIFT_FORKS_TYPE | CF_PED_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_GLASS_TYPE | CF_HORSE_TYPE | CF_HORSE_RAGDOLL_TYPE,
		CF_CAMERA_CLIPPING_TYPES = CF_VEHICLE_NON_BVH_TYPE | CF_RAGDOLL_TYPE | CF_OBJECT_TYPE | CF_PICKUP_TYPE | CF_MAP_TYPE_WEAPON | CF_RIVER_TYPE | CF_UNSMASHED_TYPE | CF_HORSE_RAGDOLL_TYPE,

		// Include flag sets for high detail map collision
		CF_HIGH_DETAIL_MAP_INCLUDE_TYPES = CF_WEAPON_TEST | CF_CAMERA_TEST | CF_PROJECTILE_TYPE,

		// Bullets and projectiles
		CF_WEAPON_AND_PROJECTILE_INCLUDE_TYPES = CF_WEAPON_TEST | CF_PROJECTILE_TYPE,
		CF_BASIC_ATTACHMENT_INCLUDE_TYPES = CF_WEAPON_TEST | CF_PROJECTILE_TYPE | CF_EXPLOSION_TYPE,
		CF_BASIC_ATTACHMENT_AND_CAMERA_INCLUDE_TYPES = CF_BASIC_ATTACHMENT_INCLUDE_TYPES | CF_CAMERA_TEST
	};

	ConstString ToString(eCollisionFlags e)
	{
		switch (e)
		{
		case CF_NONE: return "CF_NONE";
		case CF_UNUSED: return "CF_UNUSED";
		case CF_MAP_TYPE_WEAPON: return "CF_MAP_TYPE_WEAPON";
		case CF_MAP_TYPE_MOVER: return "CF_MAP_TYPE_MOVER";
		case CF_MAP_TYPE_HORSE: return "CF_MAP_TYPE_HORSE";
		case CF_MAP_TYPE_COVER: return "CF_MAP_TYPE_COVER";
		case CF_MAP_TYPE_VEHICLE: return "CF_MAP_TYPE_VEHICLE";
		case CF_VEHICLE_NON_BVH_TYPE: return "CF_VEHICLE_NON_BVH_TYPE";
		case CF_VEHICLE_BVH_TYPE: return "CF_VEHICLE_BVH_TYPE";
		case CF_BOX_VEHICLE_TYPE: return "CF_BOX_VEHICLE_TYPE";
		case CF_PED_TYPE: return "CF_PED_TYPE";
		case CF_RAGDOLL_TYPE: return "CF_RAGDOLL_TYPE";
		case CF_HORSE_TYPE: return "CF_HORSE_TYPE";
		case CF_HORSE_RAGDOLL_TYPE: return "CF_HORSE_RAGDOLL_TYPE";
		case CF_OBJECT_TYPE: return "CF_OBJECT_TYPE";
		case CF_ENVCLOTH_OBJECT_TYPE: return "CF_ENVCLOTH_OBJECT_TYPE";
		case CF_PLANT_TYPE: return "CF_PLANT_TYPE";
		case CF_PROJECTILE_TYPE: return "CF_PROJECTILE_TYPE";
		case CF_EXPLOSION_TYPE: return "CF_EXPLOSION_TYPE";
		case CF_PICKUP_TYPE: return "CF_PICKUP_TYPE";
		case CF_FOLIAGE_TYPE: return "CF_FOLIAGE_TYPE";
		case CF_FORKLIFT_FORKS_TYPE: return "CF_FORKLIFT_FORKS_TYPE";
		case CF_WEAPON_TEST: return "CF_WEAPON_TEST";
		case CF_CAMERA_TEST: return "CF_CAMERA_TEST";
		case CF_AI_TEST: return "CF_AI_TEST";
		case CF_SCRIPT_TEST: return "CF_SCRIPT_TEST";
		case CF_WHEEL_TEST: return "CF_WHEEL_TEST";
		case CF_GLASS_TYPE: return "CF_GLASS_TYPE";
		case CF_RIVER_TYPE: return "CF_RIVER_TYPE";
		case CF_SMOKE_TYPE: return "CF_SMOKE_TYPE";
		case CF_UNSMASHED_TYPE: return "CF_UNSMASHED_TYPE";
		case CF_STAIR_SLOPE_TYPE: return "CF_STAIR_SLOPE_TYPE";
		case CF_DEEP_SURFACE_TYPE: return "CF_DEEP_SURFACE_TYPE";
		case CF_ALL: return "CF_ALL";
		}
		AM_UNREACHABLE("Failed to convert eCollisionFlags (%i)", e);
	}

	bool FromString(ConstString str, eCollisionFlags& e)
	{
		u32 key = atStringHash(str);
		switch (key)
		{
		case atStringHash("CF_NONE"): e = CF_NONE; return true;
		case atStringHash("CF_UNUSED"): e = CF_UNUSED; return true;
		case atStringHash("CF_MAP_TYPE_WEAPON"): e = CF_MAP_TYPE_WEAPON; return true;
		case atStringHash("CF_MAP_TYPE_MOVER"): e = CF_MAP_TYPE_MOVER; return true;
		case atStringHash("CF_MAP_TYPE_HORSE"): e = CF_MAP_TYPE_HORSE; return true;
		case atStringHash("CF_MAP_TYPE_COVER"): e = CF_MAP_TYPE_COVER; return true;
		case atStringHash("CF_MAP_TYPE_VEHICLE"): e = CF_MAP_TYPE_VEHICLE; return true;
		case atStringHash("CF_VEHICLE_NON_BVH_TYPE"): e = CF_VEHICLE_NON_BVH_TYPE; return true;
		case atStringHash("CF_VEHICLE_BVH_TYPE"): e = CF_VEHICLE_BVH_TYPE; return true;
		case atStringHash("CF_BOX_VEHICLE_TYPE"): e = CF_BOX_VEHICLE_TYPE; return true;
		case atStringHash("CF_PED_TYPE"): e = CF_PED_TYPE; return true;
		case atStringHash("CF_RAGDOLL_TYPE"): e = CF_RAGDOLL_TYPE; return true;
		case atStringHash("CF_HORSE_TYPE"): e = CF_HORSE_TYPE; return true;
		case atStringHash("CF_HORSE_RAGDOLL_TYPE"): e = CF_HORSE_RAGDOLL_TYPE; return true;
		case atStringHash("CF_OBJECT_TYPE"): e = CF_OBJECT_TYPE; return true;
		case atStringHash("CF_ENVCLOTH_OBJECT_TYPE"): e = CF_ENVCLOTH_OBJECT_TYPE; return true;
		case atStringHash("CF_PLANT_TYPE"): e = CF_PLANT_TYPE; return true;
		case atStringHash("CF_PROJECTILE_TYPE"): e = CF_PROJECTILE_TYPE; return true;
		case atStringHash("CF_EXPLOSION_TYPE"): e = CF_EXPLOSION_TYPE; return true;
		case atStringHash("CF_PICKUP_TYPE"): e = CF_PICKUP_TYPE; return true;
		case atStringHash("CF_FOLIAGE_TYPE"): e = CF_FOLIAGE_TYPE; return true;
		case atStringHash("CF_FORKLIFT_FORKS_TYPE"): e = CF_FORKLIFT_FORKS_TYPE; return true;
		case atStringHash("CF_WEAPON_TEST"): e = CF_WEAPON_TEST; return true;
		case atStringHash("CF_CAMERA_TEST"): e = CF_CAMERA_TEST; return true;
		case atStringHash("CF_AI_TEST"): e = CF_AI_TEST; return true;
		case atStringHash("CF_SCRIPT_TEST"): e = CF_SCRIPT_TEST; return true;
		case atStringHash("CF_WHEEL_TEST"): e = CF_WHEEL_TEST; return true;
		case atStringHash("CF_GLASS_TYPE"): e = CF_GLASS_TYPE; return true;
		case atStringHash("CF_RIVER_TYPE"): e = CF_RIVER_TYPE; return true;
		case atStringHash("CF_SMOKE_TYPE"): e = CF_SMOKE_TYPE; return true;
		case atStringHash("CF_UNSMASHED_TYPE"): e = CF_UNSMASHED_TYPE; return true;
		case atStringHash("CF_STAIR_SLOPE_TYPE"): e = CF_STAIR_SLOPE_TYPE; return true;
		case atStringHash("CF_DEEP_SURFACE_TYPE"): e = CF_DEEP_SURFACE_TYPE; return true;
		}
		return false;
	}
}
