// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: filedevice.proto

#include "filedevice.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace rageam {
namespace remote {

inline constexpr FileSearchResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : filedata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileSearchResponse::FileSearchResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileSearchResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileSearchResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileSearchResponseDefaultTypeInternal() {}
  union {
    FileSearchResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileSearchResponseDefaultTypeInternal _FileSearchResponse_default_instance_;

inline constexpr FileSearchRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pattern_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        recurse_{false},
        includeflags_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileSearchRequest::FileSearchRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileSearchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileSearchRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileSearchRequestDefaultTypeInternal() {}
  union {
    FileSearchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileSearchRequestDefaultTypeInternal _FileSearchRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR FileScanResponse::FileScanResponse(::_pbi::ConstantInitialized) {}
struct FileScanResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileScanResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileScanResponseDefaultTypeInternal() {}
  union {
    FileScanResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileScanResponseDefaultTypeInternal _FileScanResponse_default_instance_;

inline constexpr FileScanRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileScanRequest::FileScanRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileScanRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileScanRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileScanRequestDefaultTypeInternal() {}
  union {
    FileScanRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileScanRequestDefaultTypeInternal _FileScanRequest_default_instance_;

inline constexpr FileExistsRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileExistsRequest::FileExistsRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileExistsRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileExistsRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileExistsRequestDefaultTypeInternal() {}
  union {
    FileExistsRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileExistsRequestDefaultTypeInternal _FileExistsRequest_default_instance_;

inline constexpr FileExistResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : value_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR FileExistResponse::FileExistResponse(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FileExistResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileExistResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileExistResponseDefaultTypeInternal() {}
  union {
    FileExistResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileExistResponseDefaultTypeInternal _FileExistResponse_default_instance_;
}  // namespace remote
}  // namespace rageam
static ::_pb::Metadata file_level_metadata_filedevice_2eproto[6];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_filedevice_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_filedevice_2eproto = nullptr;
const ::uint32_t TableStruct_filedevice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileScanRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileScanRequest, _impl_.path_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileScanResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchRequest, _impl_.path_),
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchRequest, _impl_.pattern_),
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchRequest, _impl_.recurse_),
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchRequest, _impl_.includeflags_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileSearchResponse, _impl_.filedata_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileExistsRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileExistsRequest, _impl_.path_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileExistResponse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::rageam::remote::FileExistResponse, _impl_.value_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::rageam::remote::FileScanRequest)},
        {9, -1, -1, sizeof(::rageam::remote::FileScanResponse)},
        {17, -1, -1, sizeof(::rageam::remote::FileSearchRequest)},
        {29, -1, -1, sizeof(::rageam::remote::FileSearchResponse)},
        {38, -1, -1, sizeof(::rageam::remote::FileExistsRequest)},
        {47, -1, -1, sizeof(::rageam::remote::FileExistResponse)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::rageam::remote::_FileScanRequest_default_instance_._instance,
    &::rageam::remote::_FileScanResponse_default_instance_._instance,
    &::rageam::remote::_FileSearchRequest_default_instance_._instance,
    &::rageam::remote::_FileSearchResponse_default_instance_._instance,
    &::rageam::remote::_FileExistsRequest_default_instance_._instance,
    &::rageam::remote::_FileExistResponse_default_instance_._instance,
};
const char descriptor_table_protodef_filedevice_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\020filedevice.proto\022\rrageam.remote\"\037\n\017Fil"
    "eScanRequest\022\014\n\004Path\030\001 \001(\t\"\022\n\020FileScanRe"
    "sponse\"Y\n\021FileSearchRequest\022\014\n\004Path\030\001 \001("
    "\t\022\017\n\007Pattern\030\002 \001(\t\022\017\n\007Recurse\030\003 \001(\010\022\024\n\014I"
    "ncludeFlags\030\004 \001(\005\"&\n\022FileSearchResponse\022"
    "\020\n\010FileData\030\001 \001(\014\"!\n\021FileExistsRequest\022\014"
    "\n\004Path\030\001 \001(\t\"\"\n\021FileExistResponse\022\r\n\005Val"
    "ue\030\001 \001(\010*_\n\026FileSearchIncludeFlags\022\010\n\004No"
    "ne\020\000\022\010\n\004File\020\001\022\013\n\007Archive\020\002\022\r\n\tDirectory"
    "\020\004\022\014\n\010Resource\020\010\022\007\n\003All\020\0172\211\002\n\nFileDevice"
    "\022R\n\rScanDirectory\022\036.rageam.remote.FileSc"
    "anRequest\032\037.rageam.remote.FileScanRespon"
    "se\"\000\022Q\n\006Search\022 .rageam.remote.FileSearc"
    "hRequest\032!.rageam.remote.FileSearchRespo"
    "nse\"\0000\001\022T\n\014IsFileExists\022 .rageam.remote."
    "FileExistsRequest\032 .rageam.remote.FileEx"
    "istResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_filedevice_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_filedevice_2eproto = {
    false,
    false,
    661,
    descriptor_table_protodef_filedevice_2eproto,
    "filedevice.proto",
    &descriptor_table_filedevice_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_filedevice_2eproto::offsets,
    file_level_metadata_filedevice_2eproto,
    file_level_enum_descriptors_filedevice_2eproto,
    file_level_service_descriptors_filedevice_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_filedevice_2eproto_getter() {
  return &descriptor_table_filedevice_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_filedevice_2eproto(&descriptor_table_filedevice_2eproto);
namespace rageam {
namespace remote {
const ::google::protobuf::EnumDescriptor* FileSearchIncludeFlags_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_filedevice_2eproto);
  return file_level_enum_descriptors_filedevice_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t FileSearchIncludeFlags_internal_data_[] = {
    196608u, 32u, 4130u, };
bool FileSearchIncludeFlags_IsValid(int value) {
  return 0 <= value && value <= 15 && ((33047u >> value) & 1) != 0;
}
// ===================================================================

class FileScanRequest::_Internal {
 public:
};

FileScanRequest::FileScanRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileScanRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileScanRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : path_(arena, from.path_),
        _cached_size_{0} {}

FileScanRequest::FileScanRequest(
    ::google::protobuf::Arena* arena,
    const FileScanRequest& from)
    : ::google::protobuf::Message(arena) {
  FileScanRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:rageam.remote.FileScanRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileScanRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        _cached_size_{0} {}

inline void FileScanRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileScanRequest::~FileScanRequest() {
  // @@protoc_insertion_point(destructor:rageam.remote.FileScanRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileScanRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileScanRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rageam.remote.FileScanRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileScanRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 42, 2> FileScanRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileScanRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string Path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileScanRequest, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Path = 1;
    {PROTOBUF_FIELD_OFFSET(FileScanRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\35\4\0\0\0\0\0\0"
    "rageam.remote.FileScanRequest"
    "Path"
  }},
};

::uint8_t* FileScanRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rageam.remote.FileScanRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rageam.remote.FileScanRequest.Path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rageam.remote.FileScanRequest)
  return target;
}

::size_t FileScanRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rageam.remote.FileScanRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileScanRequest::_class_data_ = {
    FileScanRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileScanRequest::GetClassData() const {
  return &_class_data_;
}

void FileScanRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileScanRequest*>(&to_msg);
  auto& from = static_cast<const FileScanRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rageam.remote.FileScanRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileScanRequest::CopyFrom(const FileScanRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rageam.remote.FileScanRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileScanRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileScanRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileScanRequest::InternalSwap(FileScanRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata FileScanRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[0]);
}
// ===================================================================

class FileScanResponse::_Internal {
 public:
};

FileScanResponse::FileScanResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileScanResponse)
}
FileScanResponse::FileScanResponse(
    ::google::protobuf::Arena* arena,
    const FileScanResponse& from)
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
  FileScanResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:rageam.remote.FileScanResponse)
}









::google::protobuf::Metadata FileScanResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[1]);
}
// ===================================================================

class FileSearchRequest::_Internal {
 public:
};

FileSearchRequest::FileSearchRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileSearchRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : path_(arena, from.path_),
        pattern_(arena, from.pattern_),
        _cached_size_{0} {}

FileSearchRequest::FileSearchRequest(
    ::google::protobuf::Arena* arena,
    const FileSearchRequest& from)
    : ::google::protobuf::Message(arena) {
  FileSearchRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, recurse_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, recurse_),
           offsetof(Impl_, includeflags_) -
               offsetof(Impl_, recurse_) +
               sizeof(Impl_::includeflags_));

  // @@protoc_insertion_point(copy_constructor:rageam.remote.FileSearchRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        pattern_(arena),
        _cached_size_{0} {}

inline void FileSearchRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, recurse_),
           0,
           offsetof(Impl_, includeflags_) -
               offsetof(Impl_, recurse_) +
               sizeof(Impl_::includeflags_));
}
FileSearchRequest::~FileSearchRequest() {
  // @@protoc_insertion_point(destructor:rageam.remote.FileSearchRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileSearchRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.pattern_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileSearchRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rageam.remote.FileSearchRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _impl_.pattern_.ClearToEmpty();
  ::memset(&_impl_.recurse_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.includeflags_) -
      reinterpret_cast<char*>(&_impl_.recurse_)) + sizeof(_impl_.includeflags_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileSearchRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 51, 2> FileSearchRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileSearchRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int32 IncludeFlags = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileSearchRequest, _impl_.includeflags_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.includeflags_)}},
    // string Path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.path_)}},
    // string Pattern = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.pattern_)}},
    // bool Recurse = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileSearchRequest, _impl_.recurse_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.recurse_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Path = 1;
    {PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string Pattern = 2;
    {PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.pattern_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool Recurse = 3;
    {PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.recurse_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 IncludeFlags = 4;
    {PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.includeflags_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
    "\37\4\7\0\0\0\0\0"
    "rageam.remote.FileSearchRequest"
    "Path"
    "Pattern"
  }},
};

::uint8_t* FileSearchRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rageam.remote.FileSearchRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rageam.remote.FileSearchRequest.Path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string Pattern = 2;
  if (!this->_internal_pattern().empty()) {
    const std::string& _s = this->_internal_pattern();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rageam.remote.FileSearchRequest.Pattern");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // bool Recurse = 3;
  if (this->_internal_recurse() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        3, this->_internal_recurse(), target);
  }

  // int32 IncludeFlags = 4;
  if (this->_internal_includeflags() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<4>(
            stream, this->_internal_includeflags(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rageam.remote.FileSearchRequest)
  return target;
}

::size_t FileSearchRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rageam.remote.FileSearchRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  // string Pattern = 2;
  if (!this->_internal_pattern().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_pattern());
  }

  // bool Recurse = 3;
  if (this->_internal_recurse() != 0) {
    total_size += 2;
  }

  // int32 IncludeFlags = 4;
  if (this->_internal_includeflags() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_includeflags());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileSearchRequest::_class_data_ = {
    FileSearchRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileSearchRequest::GetClassData() const {
  return &_class_data_;
}

void FileSearchRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileSearchRequest*>(&to_msg);
  auto& from = static_cast<const FileSearchRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rageam.remote.FileSearchRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  if (!from._internal_pattern().empty()) {
    _this->_internal_set_pattern(from._internal_pattern());
  }
  if (from._internal_recurse() != 0) {
    _this->_internal_set_recurse(from._internal_recurse());
  }
  if (from._internal_includeflags() != 0) {
    _this->_internal_set_includeflags(from._internal_includeflags());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileSearchRequest::CopyFrom(const FileSearchRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rageam.remote.FileSearchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileSearchRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileSearchRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileSearchRequest::InternalSwap(FileSearchRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.pattern_, &other->_impl_.pattern_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.includeflags_)
      + sizeof(FileSearchRequest::_impl_.includeflags_)
      - PROTOBUF_FIELD_OFFSET(FileSearchRequest, _impl_.recurse_)>(
          reinterpret_cast<char*>(&_impl_.recurse_),
          reinterpret_cast<char*>(&other->_impl_.recurse_));
}

::google::protobuf::Metadata FileSearchRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[2]);
}
// ===================================================================

class FileSearchResponse::_Internal {
 public:
};

FileSearchResponse::FileSearchResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileSearchResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : filedata_(arena, from.filedata_),
        _cached_size_{0} {}

FileSearchResponse::FileSearchResponse(
    ::google::protobuf::Arena* arena,
    const FileSearchResponse& from)
    : ::google::protobuf::Message(arena) {
  FileSearchResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:rageam.remote.FileSearchResponse)
}
inline PROTOBUF_NDEBUG_INLINE FileSearchResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : filedata_(arena),
        _cached_size_{0} {}

inline void FileSearchResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileSearchResponse::~FileSearchResponse() {
  // @@protoc_insertion_point(destructor:rageam.remote.FileSearchResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileSearchResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.filedata_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileSearchResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rageam.remote.FileSearchResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.filedata_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileSearchResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileSearchResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileSearchResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bytes FileData = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.filedata_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bytes FileData = 1;
    {PROTOBUF_FIELD_OFFSET(FileSearchResponse, _impl_.filedata_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBytes | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileSearchResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rageam.remote.FileSearchResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bytes FileData = 1;
  if (!this->_internal_filedata().empty()) {
    const std::string& _s = this->_internal_filedata();
    target = stream->WriteBytesMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rageam.remote.FileSearchResponse)
  return target;
}

::size_t FileSearchResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rageam.remote.FileSearchResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bytes FileData = 1;
  if (!this->_internal_filedata().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                    this->_internal_filedata());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileSearchResponse::_class_data_ = {
    FileSearchResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileSearchResponse::GetClassData() const {
  return &_class_data_;
}

void FileSearchResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileSearchResponse*>(&to_msg);
  auto& from = static_cast<const FileSearchResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rageam.remote.FileSearchResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_filedata().empty()) {
    _this->_internal_set_filedata(from._internal_filedata());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileSearchResponse::CopyFrom(const FileSearchResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rageam.remote.FileSearchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileSearchResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileSearchResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileSearchResponse::InternalSwap(FileSearchResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filedata_, &other->_impl_.filedata_, arena);
}

::google::protobuf::Metadata FileSearchResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[3]);
}
// ===================================================================

class FileExistsRequest::_Internal {
 public:
};

FileExistsRequest::FileExistsRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileExistsRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileExistsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : path_(arena, from.path_),
        _cached_size_{0} {}

FileExistsRequest::FileExistsRequest(
    ::google::protobuf::Arena* arena,
    const FileExistsRequest& from)
    : ::google::protobuf::Message(arena) {
  FileExistsRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:rageam.remote.FileExistsRequest)
}
inline PROTOBUF_NDEBUG_INLINE FileExistsRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : path_(arena),
        _cached_size_{0} {}

inline void FileExistsRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
FileExistsRequest::~FileExistsRequest() {
  // @@protoc_insertion_point(destructor:rageam.remote.FileExistsRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileExistsRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.path_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileExistsRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:rageam.remote.FileExistsRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.path_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileExistsRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 44, 2> FileExistsRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileExistsRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string Path = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(FileExistsRequest, _impl_.path_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string Path = 1;
    {PROTOBUF_FIELD_OFFSET(FileExistsRequest, _impl_.path_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\37\4\0\0\0\0\0\0"
    "rageam.remote.FileExistsRequest"
    "Path"
  }},
};

::uint8_t* FileExistsRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rageam.remote.FileExistsRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    const std::string& _s = this->_internal_path();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "rageam.remote.FileExistsRequest.Path");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rageam.remote.FileExistsRequest)
  return target;
}

::size_t FileExistsRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rageam.remote.FileExistsRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Path = 1;
  if (!this->_internal_path().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileExistsRequest::_class_data_ = {
    FileExistsRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileExistsRequest::GetClassData() const {
  return &_class_data_;
}

void FileExistsRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileExistsRequest*>(&to_msg);
  auto& from = static_cast<const FileExistsRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rageam.remote.FileExistsRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_path().empty()) {
    _this->_internal_set_path(from._internal_path());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileExistsRequest::CopyFrom(const FileExistsRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rageam.remote.FileExistsRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileExistsRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileExistsRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileExistsRequest::InternalSwap(FileExistsRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
}

::google::protobuf::Metadata FileExistsRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[4]);
}
// ===================================================================

class FileExistResponse::_Internal {
 public:
};

FileExistResponse::FileExistResponse(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:rageam.remote.FileExistResponse)
}
FileExistResponse::FileExistResponse(
    ::google::protobuf::Arena* arena, const FileExistResponse& from)
    : FileExistResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE FileExistResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void FileExistResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.value_ = {};
}
FileExistResponse::~FileExistResponse() {
  // @@protoc_insertion_point(destructor:rageam.remote.FileExistResponse)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void FileExistResponse::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void FileExistResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:rageam.remote.FileExistResponse)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.value_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* FileExistResponse::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> FileExistResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_FileExistResponse_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool Value = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileExistResponse, _impl_.value_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(FileExistResponse, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool Value = 1;
    {PROTOBUF_FIELD_OFFSET(FileExistResponse, _impl_.value_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* FileExistResponse::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:rageam.remote.FileExistResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // bool Value = 1;
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this->_internal_value(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rageam.remote.FileExistResponse)
  return target;
}

::size_t FileExistResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rageam.remote.FileExistResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // bool Value = 1;
  if (this->_internal_value() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData FileExistResponse::_class_data_ = {
    FileExistResponse::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* FileExistResponse::GetClassData() const {
  return &_class_data_;
}

void FileExistResponse::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<FileExistResponse*>(&to_msg);
  auto& from = static_cast<const FileExistResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:rageam.remote.FileExistResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_value() != 0) {
    _this->_internal_set_value(from._internal_value());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void FileExistResponse::CopyFrom(const FileExistResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rageam.remote.FileExistResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool FileExistResponse::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* FileExistResponse::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void FileExistResponse::InternalSwap(FileExistResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.value_, other->_impl_.value_);
}

::google::protobuf::Metadata FileExistResponse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_filedevice_2eproto_getter, &descriptor_table_filedevice_2eproto_once,
      file_level_metadata_filedevice_2eproto[5]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace remote
}  // namespace rageam
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
